api-gateway
==============

:toc:
:toc-placement: preamble
:toclevels: 1
:project-artifact-name: api-gateway

// Need some preamble to get TOC:
{empty}
image:https://img.shields.io/travis/marzelwidmer/api-gateway.svg?style=flat-square["TravisCI", link="https://travis-ci.org/marzelwidmer/api-gateway"]
image:https://circleci.com/gh/marzelwidmer/api-gateway.svg?style=shield&circle-token=:circle-token["CircleCI", link="https://circleci.com/gh/marzelwidmer/api-gateway"]
image:https://api.codacy.com/project/badge/Grade/34093789c75a4b72891743de8715cc65["Codacy code quality", link="https://www.codacy.com/app/marzelwidmer/api-gateway?utm_source=github.com&utm_medium=referral&utm_content=marzelwidmer/api-gateway&utm_campaign=Badge_Grade"]
image:https://api.codacy.com/project/badge/Coverage/34093789c75a4b72891743de8715cc65["Codacy code quality", link="https://www.codacy.com/app/marzelwidmer/api-gateway?utm_source=github.com&utm_medium=referral&utm_content=marzelwidmer/api-gateway&utm_campaign=Badge_Coverage"]
image:https://coveralls.io/repos/github/marzelwidmer/api-gateway/badge.svg?branch=develop["Coverage Status", link="https://coveralls.io/github/marzelwidmer/api-gateway?branch=develop"]
image:https://badges.gitter.im/marzelwidmer/api-gateway.svg[link="https://gitter.im/marzelwidmer/api-gateway?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]



[installation]
== Installation

:spring-boot-ref-guide: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/
:spring-boot-ref-guide-executable-jar: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-first-application-executable-jar


=== Build Application:
 $ mvn package

Copy the file {project-artifact-name}.jar anywhere on the server.
The JAR already contains the configuration for all available environments.
For further information please visit the  {spring-boot-ref-guide}[Spring Boot Reference Guide]

=== Start Application
==== Default Profile
Start application on command line. The _default_ profile supports a H2 datbase.
For more information please visit the {spring-boot-ref-guide-executable-jar}[Spring Boot Reference Guide] for further information.

    $ java -jar -Dspring.profiles.active=production api-gateway.jar

There are additional Spring profiles available.

