api-gateway
============

:toc:
:toc-placement: preamble
:toclevels: 1
:project-artifact-name: api-gateway

// Need some preamble to get TOC:
{empty}
image:https://circleci.com/gh/marzelwidmer/api-gateway.svg?style=shield&circle-token=:circle-token["CircleCI", link="https://circleci.com/gh/marzelwidmer/api-gateway"]
image:https://api.codacy.com/project/badge/Grade/016e33a40e1b402ba8938ab69bdd0deb["Codacy code quality", link="https://www.codacy.com/app/marzelwidmer/api-gateway?utm_source=github.com&utm_medium=referral&utm_content=marzelwidmer/api-gateway&utm_campaign=Badge_Grade"]
image:https://api.codacy.com/project/badge/Coverage/016e33a40e1b402ba8938ab69bdd0deb["Codacy code quality", link="https://www.codacy.com/app/marzelwidmer/api-gateway?utm_source=github.com&utm_medium=referral&utm_content=marzelwidmer/api-gateway&utm_campaign=Badge_Coverage"]

[installation]
== Installation

:spring-boot-ref-guide: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/
:spring-boot-ref-guide-executable-jar: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-first-application-executable-jar


=== Build Application:
 $ mvn package

Copy the file {project-artifact-name}.jar anywhere on the server.
The JAR already contains the configuration for all available environments.
For further information please visit the  {spring-boot-ref-guide}[Spring Boot Reference Guide]

=== Start Application
==== Default Profile
Start application on command line. The _default_ profile supports a H2 datbase.
For more information please visit the {spring-boot-ref-guide-executable-jar}[Spring Boot Reference Guide] for further information.

    $ java -jar -Dspring.profiles.active=production api-gateway.jar

There are additional Spring profiles available.



    mvn package docker:build -Pdocker

    docker run -d -p 8080:8080 marzelwidmer/api-gateway

    docker rm $(docker ps -a -q)
    docker rmi $(docker images -q) -f