server:
  port: 80

spring:
  application:
    name: @project.name@

# Infos Build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: /log/

# Management
management:
  context-path: /manage
  info:
     git:
       mode: full
  security:
    enabled: false

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true


