spring:
  application:
    name: @project.name@

# Infos Build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: /log/

# Management
management:
  context-path: /manage
  info:
     git:
       mode: full
  security:
    enabled: false

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

# Zuul
zuul:
  add-host-header: true
  add-proxy-headers: true
  host:
    socket-timeout-millis: 300000
  routes:
    price-service:
      path: /price-service/api/**
      url:  http://${server.address}:9050/api/
    # manage url's
    session-data-store-manage:
      path: /manage/session-data-store/**
      url:  http://${server.address}:9040/manage/
    price-service-manage:
      path: /manage/price-service/**
      url:  http://${server.address}:9050/manage/
    spring-boot-admin:
      path: /manage/spring-boot-admin/**
      url:  http://${server.address}:8081/spring-boot-admin
      sensitive-headers:


## Embedded Tomcat Stuff
server:
 use-forward-headers: true
 context-path: /
 port: 8080
 address: localhost
 compression:
   enabled: true
   mime-types: application/json,application/xml,text/html,text/xml,text/plain
 max-http-header-size: 16380


